export const COUNTRY_LIST_REQUEST = "COUNTRY_LIST_REQUEST";
export const COUNTRY_LIST_SUCCESS = "COUNTRY_LIST_SUCCESS";
export const COUNTRY_LIST_FAIL = "COUNTRY_LIST_FAIL";
export const COUNTRY_LIST_RESET = "COUNTRY_LIST_RESET";

export const CITY_LIST_REQUEST = "CITY_LIST_REQUEST";
export const CITY_LIST_SUCCESS = "CITY_LIST_SUCCESS";
export const CITY_LIST_FAIL = "CITY_LIST_FAIL";
export const CITY_LIST_RESET = "CITY_LIST_RESET";

export const TOWN_LIST_REQUEST = "TOWN_LIST_REQUEST";
export const TOWN_LIST_SUCCESS = "TOWN_LIST_SUCCESS";
export const TOWN_LIST_FAIL = "TOWN_LIST_FAIL";
export const TOWN_LIST_RESET = "TOWN_LIST_RESET";

export const METHODS_LIST_REQUEST = "METHODS_LIST_REQUEST";
export const METHODS_LIST_SUCCESS = "METHODS_LIST_SUCCESS";
export const METHODS_LIST_FAIL = "METHODS_LIST_FAIL";

export const GET_BY_COORDINATES_REQUEST = "GET_BY_COORDINATES_REQUEST";
export const GET_BY_COORDINATES_SUCCESS = "GET_BY_COORDINATES_SUCCESS";
export const GET_BY_COORDINATES_FAIL = "GET_BY_COORDINATES_FAIL";

export const SINGLE_TOWN_REQUEST = "SINGLE_TOWN_REQUEST";
export const SINGLE_TOWN_SUCCESS = "SINGLE_TOWN_SUCCESS";
export const SINGLE_TOWN_FAIL = "SINGLE_TOWN_FAIL";

export const GET_BY_LOCATION_REQUEST = "GET_BY_LOCATION_REQUEST";
export const GET_BY_LOCATION_SUCCESS = "GET_BY_LOCATION_SUCCESS";
export const GET_BY_LOCATION_FAIL = "GET_BY_LOCATION_FAIL";

export const GET_REVERSE_LOCATION_REQUEST = "GET_REVERSE_LOCATION_REQUEST";
export const GET_REVERSE_LOCATION_SUCCESS = "GET_REVERSE_LOCATION_SUCCESS";
export const GET_REVERSE_LOCATION_FAIL = "GET_REVERSE_LOCATION_FAIL";
export const GET_REVERSE_LOCATION_RESET = "GET_REVERSE_LOCATION_RESET";
